# Generated by Django 5.2.8 on 2026-05-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_countries'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='exchangerate',
            table='exchange_rates',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_categories',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
        migrations.AlterModelTable(
            name='productprice',
            table='product_prices',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='user_addresses',
        ),
    ]
