# Generated by Django 5.2.8 on 2026-06-03 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('payment_failed', 'Payment failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=24)),
                ('fulfillment_method', models.CharField(choices=[('delivery', 'Delivery'), ('self_pickup', 'Self pickup')], max_length=20)),
                ('payment_method', models.CharField(choices=[('tng_ewallet', 'TNG eWallet'), ('billplz_card', 'Credit/Debit card')], max_length=20)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_mobile', models.CharField(max_length=30)),
                ('delivery_addr1', models.CharField(blank=True, max_length=255)),
                ('delivery_addr2', models.CharField(blank=True, max_length=255)),
                ('delivery_postcode', models.CharField(blank=True, max_length=20)),
                ('delivery_city', models.CharField(blank=True, max_length=120)),
                ('delivery_state', models.CharField(blank=True, max_length=120)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('currency_code', models.CharField(default='MYR', max_length=3)),
                ('currency_symbol', models.CharField(default='RM', max_length=8)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(blank=True, max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('billplz', 'BillPlz')], default='billplz', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bill_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bill_url', models.URLField(blank=True, max_length=500)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
