# Generated by Django 5.2.8 on 2026-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('tng_ewallet', 'TNG eWallet'), ('senangpay_card', 'Credit/Debit card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('senangpay', 'SenangPay')], default='senangpay', max_length=20),
        ),
    ]
