# Generated by Django 5.2.8 on 2026-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_payment_bill_id_remove_payment_bill_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('tng_ewallet', 'TNG eWallet'), ('billplz_card', 'Credit/Debit card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('billplz', 'BillPlz')], default='billplz', max_length=20),
        ),
    ]
