# Generated by Django 5.2.8 on 2026-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_payment_gateway_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('billplz', 'BillPlz')], default='billplz', max_length=20),
        ),
    ]
