# Generated by Django 5.2.8 on 2026-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('billplz', 'BillPlz')], default='manual', max_length=20),
        ),
    ]
