# Generated by Django 5.2.8 on 2026-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shorten_order_status_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending payment'), ('SC', 'Success'), ('FL', 'Cancelled'), ('CN', 'Cancelled')], default='PN', max_length=2),
        ),
    ]
