# Generated by Django 5.2.8 on 2026-09-05

import django.db.models.deletion
import api.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_product_height_cm_product_length_cm_product_width_cm"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCustomization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="My Room", max_length=120)),
                ("room_image", models.FileField(storage=api.storage.private_room_storage, upload_to="room_customizations/%Y/%m/")),
                ("wall_width_cm", models.DecimalField(decimal_places=2, max_digits=9)),
                ("wall_height_cm", models.DecimalField(decimal_places=2, max_digits=9)),
                ("wall_corners", models.JSONField(default=list)),
                ("image_width_px", models.PositiveIntegerField(default=0)),
                ("image_height_px", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="room_customizations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "room_customizations", "ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="RoomCustomizationProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("position_x_cm", models.DecimalField(decimal_places=2, max_digits=9)),
                ("position_y_cm", models.DecimalField(decimal_places=2, max_digits=9)),
                ("width_cm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("height_cm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("z_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="room_customization_placements", to="api.product")),
                ("room_customization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="placements", to="api.roomcustomization")),
            ],
            options={"db_table": "room_customization_products", "ordering": ["z_index", "id"]},
        ),
    ]
