# Generated by Django 5.2.8 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_roomcustomization_roomcustomizationproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("embedding", models.JSONField(default=list)),
                ("dimensions", models.PositiveIntegerField(default=0)),
                ("model_name", models.CharField(max_length=120)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_embedding",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_embeddings",
                "ordering": ["product_id"],
            },
        ),
    ]
